version: "3.8"
services:
  db:
    image: postgres:16.3
    container_name: postgres_iphonehouse
    restart: always
    environment:
      POSTGRES_PASSWORD: 'root'
      POSTGRES_USER: 'root'  # PostgreSQL default superuser
      POSTGRES_DB: 'iphone_house'  # Default database to connect to
#      PGPORT: 3318
#      PGUSER: 'root'
    ports:
      - '3318:5432'
    expose:
      - '5432'
    volumes:
      - ./db_data:/var/lib/postgresql/data
      - ./dbpostgres/init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U root -d iphone_house"]
      interval: 30s
      timeout: 10s
      retries: 5
  pgadmin:
    depends_on:
      - db
    image: dpage/pgadmin4
    container_name: pgadmin
    restart: always
    ports:
      - '8095:80'
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
